name: Backend CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./Backend
    
    - name: Run linter
      run: npm run lint
      working-directory: ./Backend
    
    - name: Run tests
      run: npm test
      working-directory: ./Backend/tests
      env:
        CI: true

    - name: Build TypeScript
      run: npm run build
      working-directory: ./Backend