name: Frontend CI

on: 
    push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./peakptapp/app
    
    - name: Run linter
      run: npm run lint
      working-directory: peakptapp/app
    
    - name: Run tests
      run: npm test
      working-directory: peakptapp/test
      env:
        CI: true

    - name: Build Expo app
      run: npm run build
      working-directory: peakptapp/app